// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SunLab2.DAL;

#nullable disable

namespace SunLab2.DAL.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20241114200012_VirusSymptomsTableMigration1")]
    partial class VirusSymptomsTableMigration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SunLab2.DAL.Model.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("UserID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SunLab2.DAL.Model.VirusDisease", b =>
                {
                    b.Property<int>("VirusDiseaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VirusDiseaseId"));

                    b.Property<int>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("VirusDiseaseName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("VirusDiseaseId");

                    b.HasIndex("UserID");

                    b.ToTable("VirusDiseases");
                });

            modelBuilder.Entity("SunLab2.DAL.Model.VirusSymptom", b =>
                {
                    b.Property<int>("VirusSymptomID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VirusSymptomID"));

                    b.Property<int>("VirusDiseaseId")
                        .HasColumnType("int");

                    b.Property<int>("VirusSymptomSeverity")
                        .HasColumnType("int");

                    b.Property<string>("VirusSymptonName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.HasKey("VirusSymptomID");

                    b.HasIndex("VirusDiseaseId");

                    b.ToTable("VirusSymptom");
                });

            modelBuilder.Entity("SunLab2.DAL.Model.VirusDisease", b =>
                {
                    b.HasOne("SunLab2.DAL.Model.User", "User")
                        .WithMany("VirusDiseases")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SunLab2.DAL.Model.VirusSymptom", b =>
                {
                    b.HasOne("SunLab2.DAL.Model.VirusDisease", "VirusDisease")
                        .WithMany("Symptoms")
                        .HasForeignKey("VirusDiseaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VirusDisease");
                });

            modelBuilder.Entity("SunLab2.DAL.Model.User", b =>
                {
                    b.Navigation("VirusDiseases");
                });

            modelBuilder.Entity("SunLab2.DAL.Model.VirusDisease", b =>
                {
                    b.Navigation("Symptoms");
                });
#pragma warning restore 612, 618
        }
    }
}
